#ifndef NETGEN_TEST_HH_
#define NETGEN_TEST_HH_



//The two header files listed here are all that we need to set up a
//rule based model and generate the reaction network.
#include "../../NFcore/NFcore.hh"
#include "../../NFreactions/NFreactions.hh"
#include "../../NFreactions/reactions/reaction.hh"
#include "../../netgen/netgen.hh"


//NFcore is the primary namespace of the NFsim program.  It contains
//all the basic classes and functions for creating, running, and
//outputting a given system.  Be sure to use this namespace!
using namespace NFcore;



//!  Namespace for the NetGen Test System (abbreviated netgen_test) example.
/*!
	This namespace maintains functions that creates a rule based model and
	generates the corresponding reaction network.  This is currently a work in
	progress.  If you want to learn the details of NetGen,
	this is the place to start looking.  Be sure to look at these files:
	netgen_test.hh and simple_system.cpp.  Start with the run
	function in the cpp file, and follow the documentation to see how
	everything works.
	@author Justin Hogg
*/
namespace netgen_test
{

	//!  Creates a simple rule model and generates its reaction network.
	/*!
		Start here in netgen_test.cpp to see how a rule model is created and
		networks are generated by NetGen.
		@author Justin Hogg
	 */
	void run();


	/*!
		Creates Molecule of type X for the simple system.  In this system, X is the
		molecule that gets modified (in this case phosphorylated) by the enzyme.
		@author Michael Sneddon
	 */
	MoleculeType * createX(System *s);


	/*!
		Creates Molecule of type Y for the simple system.  In this system, Y is the
		enzyme that phosphorylates X.
		@author Michael Sneddon
	 */
	MoleculeType * createY(System *s);


	/*!
		Creates a simple dephosphorlyation reaction consisting of a single state change.  Look
		here first to get the basic idea of how reactions are defined and in particular, how
		simple unimolecular reactions are created.
		@author Michael Sneddon
	 */
	ReactionClass * createReactionXDephos(MoleculeType *molX, double rate);


	/*!
		Creates the binding reaction between X and Y.  Look here to see how bimolecular reactions
		such as binding reactions can be defined.
		@author Michael Sneddon
	 */
	ReactionClass * createReactionXYbind(MoleculeType *molX,MoleculeType *molY, double rate);


	/*!
		Creates an unbinding reaction between X and Y.  Look here to see how unbinding reactions
		can be defined.
		@author Michael Sneddon
	 */
	ReactionClass * createReactionXYunbind(MoleculeType *molX, MoleculeType *molY, double rate);


	/*!
		Creates the catalytic step of the enzymatic reaction in this simple system.  Look here
		to learn how to create reactions that include multiple transformations of the reactants.
		@author Michael Sneddon
	 */
	ReactionClass * createReactionYphosX(MoleculeType *molX, MoleculeType *molY, double rate);


	/*!
		Creates the observables used in the Simple System.  Look at this function to
		learn how basic observables can be created and added to the system.
		@author Michael Sneddon
	 */
	void addObs(System * s, MoleculeType *molX, MoleculeType *molY);
}


#endif /*NETGEN_TEST_HH_*/
